# Generated by Django 5.2.5 on 2025-09-02 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_element', models.CharField(max_length=110, verbose_name='Тип объекта')),
            ],
            options={
                'verbose_name': 'Элемент площади',
                'db_table': 'element_tab',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=110, unique=True, verbose_name='Название проекта')),
                ('total_square', models.FloatField(default=0, verbose_name='Общая площадь')),
                ('author', models.CharField(max_length=100, verbose_name='Автор проекта')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Проект',
                'db_table': 'project_tab',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(max_length=120, verbose_name='Характеристика')),
                ('element_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_calc.element', verbose_name='Элемент площади')),
            ],
            options={
                'verbose_name': 'Характеристика объекта',
                'verbose_name_plural': 'Характеристики объектов',
                'db_table': 'property_tab',
            },
        ),
        migrations.CreateModel(
            name='InputData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('square', models.FloatField(blank=True, null=True, verbose_name='Площадь')),
                ('length', models.FloatField(blank=True, null=True, verbose_name='Длина')),
                ('event', models.CharField(blank=True, choices=[('сохранение', 'Сохранение'), ('демонтаж', 'Демонтаж'), ('ремонт', 'Ремонт'), ('устройство', 'Устройство'), ('уничтожение', 'Уничтожение'), ('восстановление', 'Восстановление')], max_length=110, null=True, verbose_name='Тип работ')),
                ('element_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_calc.element')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_calc.project')),
                ('property_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_calc.property', verbose_name='Характеристика')),
            ],
            options={
                'verbose_name': 'Входные данные',
                'db_table': 'input_tab',
            },
        ),
    ]
